// distpool/ctrl/v1/ctrl.proto — wire schema for the /ws/agent control plane.
//
// Negotiated via the `Sec-WebSocket-Protocol: distpool.proto.v1` request
// header.  When the server accepts that subprotocol the frames on the
// WebSocket switch from JSON (the default, still supported for legacy
// rigs) to length-delimited protobuf carried in WebSocket BINARY frames.
//
// Each frame is a ClientFrame (rig → server) or ServerFrame (server →
// rig) — both top-level envelopes wrap a single `oneof body`.  This
// preserves the dispatch model of the JSON wire (the JSON "kind" field
// becomes the oneof discriminator) while giving us static types and
// 3–5× smaller frames on the wire.
//
// Frames whose payloads are still evolving (comfy_result, comfy_caps,
// p2p_signal) carry their body as opaque JSON bytes inside the proto.
// This is deliberate: the server forwards those frames to other parties
// largely untouched, and re-typing them every time a field is added is
// not worth the breakage risk during the rollout window.  Hello /
// status / relay_stats — the frames the server actually deserializes
// and operates on — get full proto schemas.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: distpool/ctrl/v1/ctrl.proto

package ctrlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CachedShardEntry — one row of a rig's on-disk shard cache.
type CachedShardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CachedShardEntry) Reset() {
	*x = CachedShardEntry{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CachedShardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedShardEntry) ProtoMessage() {}

func (x *CachedShardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedShardEntry.ProtoReflect.Descriptor instead.
func (*CachedShardEntry) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{0}
}

func (x *CachedShardEntry) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CachedShardEntry) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *CachedShardEntry) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// AgentHello — first frame on every connection.  Either a fresh pair
// (kind="hello", carries a pair token) or a reconnect (kind="resume",
// carries an agent_key).  See server/ws.go agentHello struct.
type AgentHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AgentKey        string                 `protobuf:"bytes,3,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`
	AgentId         string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NGpus           int32                  `protobuf:"varint,6,opt,name=n_gpus,json=nGpus,proto3" json:"n_gpus,omitempty"`
	VramBytes       int64                  `protobuf:"varint,7,opt,name=vram_bytes,json=vramBytes,proto3" json:"vram_bytes,omitempty"`
	PubkeyB64       string                 `protobuf:"bytes,8,opt,name=pubkey_b64,json=pubkeyB64,proto3" json:"pubkey_b64,omitempty"`
	ProtocolVersion int32                  `protobuf:"varint,9,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ClientBuild     string                 `protobuf:"bytes,10,opt,name=client_build,json=clientBuild,proto3" json:"client_build,omitempty"`
	CachedShards    []*CachedShardEntry    `protobuf:"bytes,11,rep,name=cached_shards,json=cachedShards,proto3" json:"cached_shards,omitempty"`
	// P6: SPIFFE JWT-SVID minted by the rig's local workload API socket.
	// Optional; legacy rigs omit it.  Server verifies via the configured
	// JWKS bundle and binds the SPIFFE ID to the rig row.
	SpiffeToken   string `protobuf:"bytes,12,opt,name=spiffe_token,json=spiffeToken,proto3" json:"spiffe_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{1}
}

func (x *AgentHello) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AgentHello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AgentHello) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *AgentHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentHello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentHello) GetNGpus() int32 {
	if x != nil {
		return x.NGpus
	}
	return 0
}

func (x *AgentHello) GetVramBytes() int64 {
	if x != nil {
		return x.VramBytes
	}
	return 0
}

func (x *AgentHello) GetPubkeyB64() string {
	if x != nil {
		return x.PubkeyB64
	}
	return ""
}

func (x *AgentHello) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AgentHello) GetClientBuild() string {
	if x != nil {
		return x.ClientBuild
	}
	return ""
}

func (x *AgentHello) GetCachedShards() []*CachedShardEntry {
	if x != nil {
		return x.CachedShards
	}
	return nil
}

func (x *AgentHello) GetSpiffeToken() string {
	if x != nil {
		return x.SpiffeToken
	}
	return ""
}

// AgentStatus — periodic telemetry.  See server/ws.go agentStatus.
type AgentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokensSec     float64                `protobuf:"fixed64,1,opt,name=tokens_sec,json=tokensSec,proto3" json:"tokens_sec,omitempty"`
	GpuUtil       []float64              `protobuf:"fixed64,2,rep,packed,name=gpu_util,json=gpuUtil,proto3" json:"gpu_util,omitempty"`
	NGpus         int32                  `protobuf:"varint,3,opt,name=n_gpus,json=nGpus,proto3" json:"n_gpus,omitempty"`
	GpuModel      string                 `protobuf:"bytes,4,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`
	VramTotal     int64                  `protobuf:"varint,5,opt,name=vram_total,json=vramTotal,proto3" json:"vram_total,omitempty"`
	VramFree      int64                  `protobuf:"varint,6,opt,name=vram_free,json=vramFree,proto3" json:"vram_free,omitempty"`
	UptimeSec     int64                  `protobuf:"varint,7,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	Roles         []string               `protobuf:"bytes,8,rep,name=roles,proto3" json:"roles,omitempty"`
	Models        []string               `protobuf:"bytes,9,rep,name=models,proto3" json:"models,omitempty"`
	Inflight      int32                  `protobuf:"varint,10,opt,name=inflight,proto3" json:"inflight,omitempty"`
	BwUpKbps      int64                  `protobuf:"varint,11,opt,name=bw_up_kbps,json=bwUpKbps,proto3" json:"bw_up_kbps,omitempty"`
	BwDnKbps      int64                  `protobuf:"varint,12,opt,name=bw_dn_kbps,json=bwDnKbps,proto3" json:"bw_dn_kbps,omitempty"`
	LastError     string                 `protobuf:"bytes,13,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	NatType       string                 `protobuf:"bytes,14,opt,name=nat_type,json=natType,proto3" json:"nat_type,omitempty"`
	RelayCapable  bool                   `protobuf:"varint,15,opt,name=relay_capable,json=relayCapable,proto3" json:"relay_capable,omitempty"`
	CoturnPort    int32                  `protobuf:"varint,16,opt,name=coturn_port,json=coturnPort,proto3" json:"coturn_port,omitempty"`
	PublicIp      string                 `protobuf:"bytes,17,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	CachedShards  []*CachedShardEntry    `protobuf:"bytes,18,rep,name=cached_shards,json=cachedShards,proto3" json:"cached_shards,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,19,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{2}
}

func (x *AgentStatus) GetTokensSec() float64 {
	if x != nil {
		return x.TokensSec
	}
	return 0
}

func (x *AgentStatus) GetGpuUtil() []float64 {
	if x != nil {
		return x.GpuUtil
	}
	return nil
}

func (x *AgentStatus) GetNGpus() int32 {
	if x != nil {
		return x.NGpus
	}
	return 0
}

func (x *AgentStatus) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *AgentStatus) GetVramTotal() int64 {
	if x != nil {
		return x.VramTotal
	}
	return 0
}

func (x *AgentStatus) GetVramFree() int64 {
	if x != nil {
		return x.VramFree
	}
	return 0
}

func (x *AgentStatus) GetUptimeSec() int64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

func (x *AgentStatus) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AgentStatus) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *AgentStatus) GetInflight() int32 {
	if x != nil {
		return x.Inflight
	}
	return 0
}

func (x *AgentStatus) GetBwUpKbps() int64 {
	if x != nil {
		return x.BwUpKbps
	}
	return 0
}

func (x *AgentStatus) GetBwDnKbps() int64 {
	if x != nil {
		return x.BwDnKbps
	}
	return 0
}

func (x *AgentStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *AgentStatus) GetNatType() string {
	if x != nil {
		return x.NatType
	}
	return ""
}

func (x *AgentStatus) GetRelayCapable() bool {
	if x != nil {
		return x.RelayCapable
	}
	return false
}

func (x *AgentStatus) GetCoturnPort() int32 {
	if x != nil {
		return x.CoturnPort
	}
	return 0
}

func (x *AgentStatus) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *AgentStatus) GetCachedShards() []*CachedShardEntry {
	if x != nil {
		return x.CachedShards
	}
	return nil
}

func (x *AgentStatus) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

// RelayStats — relay rig reporting per-session byte counters.
type RelayStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	BytesL2R      int64                  `protobuf:"varint,2,opt,name=bytes_l2r,json=bytesL2r,proto3" json:"bytes_l2r,omitempty"`
	BytesR2L      int64                  `protobuf:"varint,3,opt,name=bytes_r2l,json=bytesR2l,proto3" json:"bytes_r2l,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStats) Reset() {
	*x = RelayStats{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStats) ProtoMessage() {}

func (x *RelayStats) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStats.ProtoReflect.Descriptor instead.
func (*RelayStats) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{3}
}

func (x *RelayStats) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RelayStats) GetBytesL2R() int64 {
	if x != nil {
		return x.BytesL2R
	}
	return 0
}

func (x *RelayStats) GetBytesR2L() int64 {
	if x != nil {
		return x.BytesR2L
	}
	return 0
}

// OpaqueJSON — body carried as a JSON document, for frames whose
// schema is still in motion (comfy_result, comfy_caps, p2p_signal).
// The rig serializes the same map it would have sent over the JSON
// wire; the server json.Unmarshal's it the same way.
type OpaqueJSON struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpaqueJSON) Reset() {
	*x = OpaqueJSON{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpaqueJSON) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpaqueJSON) ProtoMessage() {}

func (x *OpaqueJSON) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpaqueJSON.ProtoReflect.Descriptor instead.
func (*OpaqueJSON) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{4}
}

func (x *OpaqueJSON) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

// ClientFrame — anything the rig sends to the server.
type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ClientFrame_Hello
	//	*ClientFrame_Status
	//	*ClientFrame_RelayStats
	//	*ClientFrame_ComfyResult
	//	*ClientFrame_ComfyCaps
	//	*ClientFrame_P2PSignal
	Body          isClientFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{5}
}

func (x *ClientFrame) GetBody() isClientFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClientFrame) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientFrame) GetStatus() *AgentStatus {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ClientFrame) GetRelayStats() *RelayStats {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_RelayStats); ok {
			return x.RelayStats
		}
	}
	return nil
}

func (x *ClientFrame) GetComfyResult() *OpaqueJSON {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_ComfyResult); ok {
			return x.ComfyResult
		}
	}
	return nil
}

func (x *ClientFrame) GetComfyCaps() *OpaqueJSON {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_ComfyCaps); ok {
			return x.ComfyCaps
		}
	}
	return nil
}

func (x *ClientFrame) GetP2PSignal() *OpaqueJSON {
	if x != nil {
		if x, ok := x.Body.(*ClientFrame_P2PSignal); ok {
			return x.P2PSignal
		}
	}
	return nil
}

type isClientFrame_Body interface {
	isClientFrame_Body()
}

type ClientFrame_Hello struct {
	Hello *AgentHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientFrame_Status struct {
	Status *AgentStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type ClientFrame_RelayStats struct {
	RelayStats *RelayStats `protobuf:"bytes,3,opt,name=relay_stats,json=relayStats,proto3,oneof"`
}

type ClientFrame_ComfyResult struct {
	ComfyResult *OpaqueJSON `protobuf:"bytes,4,opt,name=comfy_result,json=comfyResult,proto3,oneof"`
}

type ClientFrame_ComfyCaps struct {
	ComfyCaps *OpaqueJSON `protobuf:"bytes,5,opt,name=comfy_caps,json=comfyCaps,proto3,oneof"`
}

type ClientFrame_P2PSignal struct {
	P2PSignal *OpaqueJSON `protobuf:"bytes,6,opt,name=p2p_signal,json=p2pSignal,proto3,oneof"`
}

func (*ClientFrame_Hello) isClientFrame_Body() {}

func (*ClientFrame_Status) isClientFrame_Body() {}

func (*ClientFrame_RelayStats) isClientFrame_Body() {}

func (*ClientFrame_ComfyResult) isClientFrame_Body() {}

func (*ClientFrame_ComfyCaps) isClientFrame_Body() {}

func (*ClientFrame_P2PSignal) isClientFrame_Body() {}

// Welcome — successful hello/resume reply; carries the agent_key that
// the rig must use on every subsequent resume.
type Welcome struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentKey           string                 `protobuf:"bytes,1,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`
	UserId             int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName        string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	NegotiatedProtocol int32                  `protobuf:"varint,4,opt,name=negotiated_protocol,json=negotiatedProtocol,proto3" json:"negotiated_protocol,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{6}
}

func (x *Welcome) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *Welcome) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Welcome) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Welcome) GetNegotiatedProtocol() int32 {
	if x != nil {
		return x.NegotiatedProtocol
	}
	return 0
}

// ErrorFrame — sent before closing the connection on auth/protocol
// failures.  Named with the Frame suffix to avoid colliding with Go's
// builtin `error` type after codegen.
type ErrorFrame struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ServerProtocolMin int32                  `protobuf:"varint,2,opt,name=server_protocol_min,json=serverProtocolMin,proto3" json:"server_protocol_min,omitempty"`
	ServerProtocolMax int32                  `protobuf:"varint,3,opt,name=server_protocol_max,json=serverProtocolMax,proto3" json:"server_protocol_max,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ErrorFrame) Reset() {
	*x = ErrorFrame{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFrame) ProtoMessage() {}

func (x *ErrorFrame) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFrame.ProtoReflect.Descriptor instead.
func (*ErrorFrame) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorFrame) GetServerProtocolMin() int32 {
	if x != nil {
		return x.ServerProtocolMin
	}
	return 0
}

func (x *ErrorFrame) GetServerProtocolMax() int32 {
	if x != nil {
		return x.ServerProtocolMax
	}
	return 0
}

// Challenge — for signed-identity rigs: server sends a nonce, rig
// signs with its private key and replies with a ChallengeResponse
// (carried as OpaqueJSON for now).
type Challenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{8}
}

func (x *Challenge) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// Command — server-to-rig directive (join-pool, leave-pool, ping, …).
// Payload is opaque to keep the wire stable as new commands ship.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{9}
}

func (x *Command) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ServerFrame — anything the server sends to the rig.
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Welcome
	//	*ServerFrame_Error
	//	*ServerFrame_Challenge
	//	*ServerFrame_Command
	//	*ServerFrame_Other
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_distpool_ctrl_v1_ctrl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP(), []int{10}
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerFrame) GetError() *ErrorFrame {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerFrame) GetChallenge() *Challenge {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *ServerFrame) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerFrame) GetOther() *OpaqueJSON {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Other); ok {
			return x.Other
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerFrame_Error struct {
	Error *ErrorFrame `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type ServerFrame_Challenge struct {
	Challenge *Challenge `protobuf:"bytes,3,opt,name=challenge,proto3,oneof"`
}

type ServerFrame_Command struct {
	Command *Command `protobuf:"bytes,4,opt,name=command,proto3,oneof"`
}

type ServerFrame_Other struct {
	Other *OpaqueJSON `protobuf:"bytes,5,opt,name=other,proto3,oneof"`
}

func (*ServerFrame_Welcome) isServerFrame_Body() {}

func (*ServerFrame_Error) isServerFrame_Body() {}

func (*ServerFrame_Challenge) isServerFrame_Body() {}

func (*ServerFrame_Command) isServerFrame_Body() {}

func (*ServerFrame_Other) isServerFrame_Body() {}

var File_distpool_ctrl_v1_ctrl_proto protoreflect.FileDescriptor

const file_distpool_ctrl_v1_ctrl_proto_rawDesc = "" +
	"\n" +
	"\x1bdistpool/ctrl/v1/ctrl.proto\x12\x10distpool.ctrl.v1\"[\n" +
	"\x10CachedShardEntry\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"\x99\x03\n" +
	"\n" +
	"AgentHello\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\tagent_key\x18\x03 \x01(\tR\bagentKey\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\x12\x15\n" +
	"\x06n_gpus\x18\x06 \x01(\x05R\x05nGpus\x12\x1d\n" +
	"\n" +
	"vram_bytes\x18\a \x01(\x03R\tvramBytes\x12\x1d\n" +
	"\n" +
	"pubkey_b64\x18\b \x01(\tR\tpubkeyB64\x12)\n" +
	"\x10protocol_version\x18\t \x01(\x05R\x0fprotocolVersion\x12!\n" +
	"\fclient_build\x18\n" +
	" \x01(\tR\vclientBuild\x12G\n" +
	"\rcached_shards\x18\v \x03(\v2\".distpool.ctrl.v1.CachedShardEntryR\fcachedShards\x12!\n" +
	"\fspiffe_token\x18\f \x01(\tR\vspiffeToken\"\xe9\x04\n" +
	"\vAgentStatus\x12\x1d\n" +
	"\n" +
	"tokens_sec\x18\x01 \x01(\x01R\ttokensSec\x12\x19\n" +
	"\bgpu_util\x18\x02 \x03(\x01R\agpuUtil\x12\x15\n" +
	"\x06n_gpus\x18\x03 \x01(\x05R\x05nGpus\x12\x1b\n" +
	"\tgpu_model\x18\x04 \x01(\tR\bgpuModel\x12\x1d\n" +
	"\n" +
	"vram_total\x18\x05 \x01(\x03R\tvramTotal\x12\x1b\n" +
	"\tvram_free\x18\x06 \x01(\x03R\bvramFree\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\a \x01(\x03R\tuptimeSec\x12\x14\n" +
	"\x05roles\x18\b \x03(\tR\x05roles\x12\x16\n" +
	"\x06models\x18\t \x03(\tR\x06models\x12\x1a\n" +
	"\binflight\x18\n" +
	" \x01(\x05R\binflight\x12\x1c\n" +
	"\n" +
	"bw_up_kbps\x18\v \x01(\x03R\bbwUpKbps\x12\x1c\n" +
	"\n" +
	"bw_dn_kbps\x18\f \x01(\x03R\bbwDnKbps\x12\x1d\n" +
	"\n" +
	"last_error\x18\r \x01(\tR\tlastError\x12\x19\n" +
	"\bnat_type\x18\x0e \x01(\tR\anatType\x12#\n" +
	"\rrelay_capable\x18\x0f \x01(\bR\frelayCapable\x12\x1f\n" +
	"\vcoturn_port\x18\x10 \x01(\x05R\n" +
	"coturnPort\x12\x1b\n" +
	"\tpublic_ip\x18\x11 \x01(\tR\bpublicIp\x12G\n" +
	"\rcached_shards\x18\x12 \x03(\v2\".distpool.ctrl.v1.CachedShardEntryR\fcachedShards\x12%\n" +
	"\x0emax_concurrent\x18\x13 \x01(\x05R\rmaxConcurrent\"e\n" +
	"\n" +
	"RelayStats\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tbytes_l2r\x18\x02 \x01(\x03R\bbytesL2r\x12\x1b\n" +
	"\tbytes_r2l\x18\x03 \x01(\x03R\bbytesR2l\" \n" +
	"\n" +
	"OpaqueJSON\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"\x86\x03\n" +
	"\vClientFrame\x124\n" +
	"\x05hello\x18\x01 \x01(\v2\x1c.distpool.ctrl.v1.AgentHelloH\x00R\x05hello\x127\n" +
	"\x06status\x18\x02 \x01(\v2\x1d.distpool.ctrl.v1.AgentStatusH\x00R\x06status\x12?\n" +
	"\vrelay_stats\x18\x03 \x01(\v2\x1c.distpool.ctrl.v1.RelayStatsH\x00R\n" +
	"relayStats\x12A\n" +
	"\fcomfy_result\x18\x04 \x01(\v2\x1c.distpool.ctrl.v1.OpaqueJSONH\x00R\vcomfyResult\x12=\n" +
	"\n" +
	"comfy_caps\x18\x05 \x01(\v2\x1c.distpool.ctrl.v1.OpaqueJSONH\x00R\tcomfyCaps\x12=\n" +
	"\n" +
	"p2p_signal\x18\x06 \x01(\v2\x1c.distpool.ctrl.v1.OpaqueJSONH\x00R\tp2pSignalB\x06\n" +
	"\x04body\"\x93\x01\n" +
	"\aWelcome\x12\x1b\n" +
	"\tagent_key\x18\x01 \x01(\tR\bagentKey\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12/\n" +
	"\x13negotiated_protocol\x18\x04 \x01(\x05R\x12negotiatedProtocol\"\x86\x01\n" +
	"\n" +
	"ErrorFrame\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12.\n" +
	"\x13server_protocol_min\x18\x02 \x01(\x05R\x11serverProtocolMin\x12.\n" +
	"\x13server_protocol_max\x18\x03 \x01(\x05R\x11serverProtocolMax\"!\n" +
	"\tChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"5\n" +
	"\aCommand\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\xac\x02\n" +
	"\vServerFrame\x125\n" +
	"\awelcome\x18\x01 \x01(\v2\x19.distpool.ctrl.v1.WelcomeH\x00R\awelcome\x124\n" +
	"\x05error\x18\x02 \x01(\v2\x1c.distpool.ctrl.v1.ErrorFrameH\x00R\x05error\x12;\n" +
	"\tchallenge\x18\x03 \x01(\v2\x1b.distpool.ctrl.v1.ChallengeH\x00R\tchallenge\x125\n" +
	"\acommand\x18\x04 \x01(\v2\x19.distpool.ctrl.v1.CommandH\x00R\acommand\x124\n" +
	"\x05other\x18\x05 \x01(\v2\x1c.distpool.ctrl.v1.OpaqueJSONH\x00R\x05otherB\x06\n" +
	"\x04bodyB\xb6\x01\n" +
	"\x14com.distpool.ctrl.v1B\tCtrlProtoP\x01Z1github.com/llama-distributed/server/ctrlpb;ctrlpb\xa2\x02\x03DCX\xaa\x02\x10Distpool.Ctrl.V1\xca\x02\x10Distpool\\Ctrl\\V1\xe2\x02\x1cDistpool\\Ctrl\\V1\\GPBMetadata\xea\x02\x12Distpool::Ctrl::V1b\x06proto3"

var (
	file_distpool_ctrl_v1_ctrl_proto_rawDescOnce sync.Once
	file_distpool_ctrl_v1_ctrl_proto_rawDescData []byte
)

func file_distpool_ctrl_v1_ctrl_proto_rawDescGZIP() []byte {
	file_distpool_ctrl_v1_ctrl_proto_rawDescOnce.Do(func() {
		file_distpool_ctrl_v1_ctrl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distpool_ctrl_v1_ctrl_proto_rawDesc), len(file_distpool_ctrl_v1_ctrl_proto_rawDesc)))
	})
	return file_distpool_ctrl_v1_ctrl_proto_rawDescData
}

var file_distpool_ctrl_v1_ctrl_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_distpool_ctrl_v1_ctrl_proto_goTypes = []any{
	(*CachedShardEntry)(nil), // 0: distpool.ctrl.v1.CachedShardEntry
	(*AgentHello)(nil),       // 1: distpool.ctrl.v1.AgentHello
	(*AgentStatus)(nil),      // 2: distpool.ctrl.v1.AgentStatus
	(*RelayStats)(nil),       // 3: distpool.ctrl.v1.RelayStats
	(*OpaqueJSON)(nil),       // 4: distpool.ctrl.v1.OpaqueJSON
	(*ClientFrame)(nil),      // 5: distpool.ctrl.v1.ClientFrame
	(*Welcome)(nil),          // 6: distpool.ctrl.v1.Welcome
	(*ErrorFrame)(nil),       // 7: distpool.ctrl.v1.ErrorFrame
	(*Challenge)(nil),        // 8: distpool.ctrl.v1.Challenge
	(*Command)(nil),          // 9: distpool.ctrl.v1.Command
	(*ServerFrame)(nil),      // 10: distpool.ctrl.v1.ServerFrame
}
var file_distpool_ctrl_v1_ctrl_proto_depIdxs = []int32{
	0,  // 0: distpool.ctrl.v1.AgentHello.cached_shards:type_name -> distpool.ctrl.v1.CachedShardEntry
	0,  // 1: distpool.ctrl.v1.AgentStatus.cached_shards:type_name -> distpool.ctrl.v1.CachedShardEntry
	1,  // 2: distpool.ctrl.v1.ClientFrame.hello:type_name -> distpool.ctrl.v1.AgentHello
	2,  // 3: distpool.ctrl.v1.ClientFrame.status:type_name -> distpool.ctrl.v1.AgentStatus
	3,  // 4: distpool.ctrl.v1.ClientFrame.relay_stats:type_name -> distpool.ctrl.v1.RelayStats
	4,  // 5: distpool.ctrl.v1.ClientFrame.comfy_result:type_name -> distpool.ctrl.v1.OpaqueJSON
	4,  // 6: distpool.ctrl.v1.ClientFrame.comfy_caps:type_name -> distpool.ctrl.v1.OpaqueJSON
	4,  // 7: distpool.ctrl.v1.ClientFrame.p2p_signal:type_name -> distpool.ctrl.v1.OpaqueJSON
	6,  // 8: distpool.ctrl.v1.ServerFrame.welcome:type_name -> distpool.ctrl.v1.Welcome
	7,  // 9: distpool.ctrl.v1.ServerFrame.error:type_name -> distpool.ctrl.v1.ErrorFrame
	8,  // 10: distpool.ctrl.v1.ServerFrame.challenge:type_name -> distpool.ctrl.v1.Challenge
	9,  // 11: distpool.ctrl.v1.ServerFrame.command:type_name -> distpool.ctrl.v1.Command
	4,  // 12: distpool.ctrl.v1.ServerFrame.other:type_name -> distpool.ctrl.v1.OpaqueJSON
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_distpool_ctrl_v1_ctrl_proto_init() }
func file_distpool_ctrl_v1_ctrl_proto_init() {
	if File_distpool_ctrl_v1_ctrl_proto != nil {
		return
	}
	file_distpool_ctrl_v1_ctrl_proto_msgTypes[5].OneofWrappers = []any{
		(*ClientFrame_Hello)(nil),
		(*ClientFrame_Status)(nil),
		(*ClientFrame_RelayStats)(nil),
		(*ClientFrame_ComfyResult)(nil),
		(*ClientFrame_ComfyCaps)(nil),
		(*ClientFrame_P2PSignal)(nil),
	}
	file_distpool_ctrl_v1_ctrl_proto_msgTypes[10].OneofWrappers = []any{
		(*ServerFrame_Welcome)(nil),
		(*ServerFrame_Error)(nil),
		(*ServerFrame_Challenge)(nil),
		(*ServerFrame_Command)(nil),
		(*ServerFrame_Other)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distpool_ctrl_v1_ctrl_proto_rawDesc), len(file_distpool_ctrl_v1_ctrl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_distpool_ctrl_v1_ctrl_proto_goTypes,
		DependencyIndexes: file_distpool_ctrl_v1_ctrl_proto_depIdxs,
		MessageInfos:      file_distpool_ctrl_v1_ctrl_proto_msgTypes,
	}.Build()
	File_distpool_ctrl_v1_ctrl_proto = out.File
	file_distpool_ctrl_v1_ctrl_proto_goTypes = nil
	file_distpool_ctrl_v1_ctrl_proto_depIdxs = nil
}
